### ISSUE TITLE
python multiprocessing pool.map errors 

### ISSUE THREAD

**Issue by adamplatski** [obheda12/GitDorker#37]
I have included pictures of the same errors in powershell and on centOS8.

I've also included one picture of the pool.py errors at line 48 "in mapstar return list(map(*args))" and the GitDorker.py error at line 325 " line 325, in <module> pool.map(api_search, url_dict)".

The other picture is the errors in GitDorker.py at line 140 and 164 
" line 140, in token_round_robin current_token = tokens_list[n] IndexError: list index out of range[](url)"
"line 164, in api_search headers = {"Authorization": "token " + token_round_robin()}"

←[0mTraceback (most recent call last):$$$$$$$$ Dorking In Progress $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$  3/240
  File "C:\Users\GuyWhoNotSoSmart\GitDorker\GitDorker.py", line 325, in <module>
    pool.map(api_search, url_dict)
  File "C:\Users\GuyWhoNotSoSmart\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\GuyWhoNotSoSmart\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\GuyWhoNotSoSmart\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\GuyWhoNotSoSmart\AppData\Local\Programs\Python\Python39\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Users\GuyWhoNotSoSmart\GitDorker\GitDorker.py", line 164, in api_search
    headers = {"Authorization": "token " + token_round_robin()}
  File "C:\Users\GuyWhoNotSoSmart\GitDorker\GitDorker.py", line 140, in token_round_robin
    current_token = tokens_list[n]
IndexError: list index out of range[](url)
![Screenshot (148)_LI](https://user-images.githubusercontent.com/63764441/139879916-5e151b91-d0db-4682-836b-3e380bf156ab.jpg)
![Screenshot (149)](https://user-images.githubusercontent.com/63764441/139877911-f9078d2c-5c3b-46fa-8103-83a9650e89e7.png)
![Screenshot (150)_LI](https://user-images.githubusercontent.com/63764441/139880371-7508a332-e7fb-401f-95b9-95474f0c33b8.jpg)
![Screenshot (151)_LI](https://user-images.githubusercontent.com/63764441/139880375-1d24e0e4-cf62-4aeb-921e-d3cff0ecbaf6.jpg)

**Comment by haonanduanmu** [comment]
Hi, have you solved this problem? I meet the same question. QWQ

**Comment by bakliwalp** [comment]
@haonanduanmu , I guess the issue is that you don't have any active personal access token file. Google how to create Github Personal Access Token file and add it to the `tf/tokensfile` and you are good to go then.
